#
#   - is the Model low-level API documented
#
site_name: SenseDeep DynamoDB OneTable
repo_url: https://github.com/sensedeep/dynamodb-onetable
edit_uri: ""

nav:
  - Home: index.md
  - Getting Started:
    - Quick Tour: start/quick-tour.md
    - Installing: start/install.md
    - Configuring: start/configure.md
    - Data Modeling: start/modeling.md
    - Typescript: start/typescript.md
    - Background:
      - Why OneTable?: start/why-onetable.md
      - Features: start/features.md
      - Samples: start/samples.md
      - Contribute: start/contribute.md
      - References: start/references.md
      - Contact: start/contact.md
  - API:
    - Table Class:
      - api/table/overview.md
      - Constructor:
        - api/table/constructor/constructor.md
        - Crypto: api/table/constructor/crypto.md
        - Logging: api/table/constructor/logging.md
        - Metrics: api/table/constructor/metrics.md
        - Schemas: api/table/constructor/schemas.md
        - Transforms: api/table/constructor/transforms.md
        - Value Templates: api/table/constructor/templates.md
        - Validations: api/table/constructor/validations.md
      - Schemas:
        - Data Modeling: api/table/schemas/modeling.md
        - Indexes: api/table/schemas/indexes.md
        - Params: api/table/schemas/params.md
        - Models: api/table/schemas/models.md
        - Model Attributes: api/table/schemas/attributes.md
      - Contexts: api/table/contexts.md
      - Methods: api/table/methods.md
      - Examples: api/table/examples.md
    - Model Class:
      - Overview: api/model/overview.md
      - API Parameters: api/model/params.md
      - Methods: api/model/methods.md
      - Where Clauses: api/model/where.md
      - Examples: api/model/examples.md
    - Dynamo Class:
      - Constructor: api/dynamo/overview.md
    - Error Handling: api/errors.md
  - Extensions: extensions.md
  - Services:
    - DynamoDB Consulting: services/consulting.md
  - Blog: https://www.sensedeep.com/blog

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.ico

extra_css:
  - css/all.css
extra:
  analytics:
    provider: google
    property: G-2ZZBCEQJGK
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sensedeep/dynamodb-onetable
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/sensedeepcloud
    - icon: fontawesome/brands/flipboard
      link: https://flipboard.com/@mobsense/serverless-developer-dlpuqmniz
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/sensedeep
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sensedeepcloud
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
